name: my-pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: cd backend && npm install

      - name: TS
        run: cd backend && yarn run tsc --noemit

      - name: Build
        run: cd backend && yarn run build
      

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: cd frontend && yarn install

      - name: EsLint
        run: cd frontend && yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: TS
        run: cd frontend && yarn run tsc --noemit

      - name: Build
        run: cd frontend && yarn build