name: my-pipeline

defaults:
  run:
    working-directory: ./blog-fullstack

on:
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn run install

      - name: TS
        run: yarn run tsc --noemit

      - name: Build
        run: yarn run build
      

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn run install

      - name: EsLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: TS
        run: yarn run tsc --noemit

      - name: Build
        run: yarn build