name: my-pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/backend && npm install

      - name: TS
        run: cd $GITHUB_WORKSPACE/backend && yarn run tsc --noemit

      - name: Build
        run: cd $GITHUB_WORKSPACE/backend && yarn run build
      

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/frontend && yarn install

      - name: EsLint
        run: cd $GITHUB_WORKSPACE/frontend && yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: TS
        run: cd $GITHUB_WORKSPACE/frontend && yarn run tsc --noemit

      - name: Build
        run: cd $GITHUB_WORKSPACE/frontend && yarn build